# Starter pipeline

trigger:
- rizone

variables:
  SNAP_PACKAGE_NAME: 'snap-$(Build.Repository.Name)'

pool:
  vmImage: ubuntu-latest

stages:
  - stage: BuildSnap
    jobs:
      - job: Build
        displayName: 'Build snap'
        timeoutInMinutes: 30
        steps:
        - script: |
            sudo adduser "$USER" lxd
            sudo --user "$USER" --preserve-env --preserve-env=PATH -- env -- lxd waitready
            sudo --user "$USER" --preserve-env --preserve-env=PATH -- env -- lxd init --auto
            sudo iptables -F FORWARD
            sudo iptables -P FORWARD ACCEPT
            sudo snap install snapcraft --classic $(snapcraftSnapVersion.outputs.install_flag)
          displayName: 'Set up environment'
        - script: snap list
        - script: |
            sudo --user "$USER" --preserve-env --preserve-env=PATH -- env -- snapcraft pack -v
          displayName: 'Pack snap'
        - script: |
            if ($LASTEXITCODE -ne 0) {
              cat ~/.local/state/snapcraft/log/*
            }
          displayName: 'Snapcraft logs'
          condition: succeededOrFailed()
        - script: touch .empty
        - script: |
              mkdir -p $(Build.SourcesDirectory)/target/snap
              mv *.snap $(Build.SourcesDirectory)/target/snap
              
        - task: UniversalPackages@0
          inputs:
            command: 'publish'
            publishDirectory: '$(Build.SourcesDirectory)/target/snap'
            feedsToUsePublish: 'internal'
            vstsFeedPublish: 'RittalRiZone/rizone-library'
            vstsFeedPackagePublish: '$(SNAP_PACKAGE_NAME)'
            versionOption: 'custom'
            versionPublish: '1.$(Build.BuildNumber)'
            packagePublishDescription: 'snap package'
          displayName: 'Publish snap package'